# Generated by Django 5.2.1 on 2025-06-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='default_pic.jpg', upload_to=''),
        ),
    ]
